#!/bin/bash

echo "Checking CONTRIBUTOR status..."
echo "(specifically in these commits:"
git log --pretty=format:' %h - %s (%aN <%aE>)' ${TRAVIS_COMMIT_RANGE}
echo " ...)"
echo

passchar="\xe2\x9c\x94" # U+2714 - ballot check
failchar="\xe2\x9c\x98" # U+2718 - ballot x

failed=
IFS=$'\n'
for x in $(git log --pretty=format:'%aE %h - %s (%aN <%aE>)' ${TRAVIS_COMMIT_RANGE}); do
	email=${x%% *}
	desc=${x#* }
	if grep -q '^[^#].*<'${email}'>' allowed; then
		echo -e "\033[32m${passchar}\033[0m $desc"
	else
		echo -e "\033[31m${failchar}\033[0m $desc"
		echo -e "  \033[31m<${email}> not listed in CONTRIBUTORS file!\033[0m"
		failed=y
	fi
done

if [[ -z ${failed} ]]; then
	echo "CLA found!"
	exit 0
fi

echo "No CLA found... :sadpanda:"
exit 1
